import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';
const require_ = createRequire(import.meta.url);
const dirs = execSync('ls -d ~/.npm/_npx/*/node_modules/playwright 2>/dev/null', { shell: '/bin/bash' }).toString().trim().split('\n').filter(Boolean);
const { chromium } = require_(dirs.find((d) => existsSync(d)));
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1600, height: 1000 } });
const page = await ctx.newPage();
await page.goto('https://localhost:9664/login', { waitUntil: 'domcontentloaded' });
await page.getByLabel(/username|email/i).first().fill('admin');
await page.getByLabel(/password/i).first().fill('admin');
await page.locator('button[type="submit"]').first().click();
await page.waitForURL((u) => !String(u).includes('/login'), { timeout: 60000 });
await page.goto('https://localhost:9664/organizations/default/projects/claimflow/workflow-tasks', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(9000);
const cards = await page.getByText(/Pick an integration/).count();
console.log('project-level Human Tasks shows the dashboard:', cards > 0);
await page.screenshot({ path: '.local/project-tasks-dashboard.png' });
await browser.close();
